language: node_js
node_js: '0.10'
before_script:
- bower install
before_deploy: sh ./scripts/ci-build.sh
deploy:
- provider: divshot
  api_key:
    secure: Q2V3btwIb0Eem5tuiFPmpvoWKPd/ciDzgajy4z+IkelxLRCpQ9uHqVuQa61/J6CXiAIPAwDwJKwPEn0aYzwgYAtfmRjm7kfxvp2G3j/8MfKsntQbt7Nf4csl0UAJzynRuKnRcnirPIWNlB4tMk6pFdORZPlwLxRfhoFJabPlpRE=
  environment: development
  on:
    repo: valet-io/pledge-app
    branch: development
