
language: node_js
node_js: '0.10'
before_install:
- npm install -g bower
before_script:
- export PATH=$(npm bin):$PATH
- bower install
script:
- karma start --single-run
- karma start karma.sauce.conf.js
- sh ./scripts/ci-serve.sh
- sh ./scripts/ci-e2e-local.sh
cache:
  directories:
  - node_modules
before_deploy: sh ./scripts/ci-build.sh
deploy:
- provider: divshot
  environment: development
  api_key:
    secure: Q2V3btwIb0Eem5tuiFPmpvoWKPd/ciDzgajy4z+IkelxLRCpQ9uHqVuQa61/J6CXiAIPAwDwJKwPEn0aYzwgYAtfmRjm7kfxvp2G3j/8MfKsntQbt7Nf4csl0UAJzynRuKnRcnirPIWNlB4tMk6pFdORZPlwLxRfhoFJabPlpRE=
  skip_cleanup: true
  on:
    repo: valet-io/pledge-app
    branch: development
- provider: divshot
  environment: staging
  api_key:
    secure: Q2V3btwIb0Eem5tuiFPmpvoWKPd/ciDzgajy4z+IkelxLRCpQ9uHqVuQa61/J6CXiAIPAwDwJKwPEn0aYzwgYAtfmRjm7kfxvp2G3j/8MfKsntQbt7Nf4csl0UAJzynRuKnRcnirPIWNlB4tMk6pFdORZPlwLxRfhoFJabPlpRE=
  skip_cleanup: true
  on:
    repo: valet-io/pledge-app
    branch: master
notifications:
  slack:
    secure: XvYmKkmnZX9gpf9FaD1JNOea40KE4qs/imKA6tojEYuP3nuqXcc+ONZjH8ZgBu40o9EY2elgW5a8kI5ckEMLj6bk8nZ3AnEr7SP6ROQMYNNjLVh8YTYzcCDI89XFBzTrbTvbkIwvu0aSIxf9Icu1NfLg0C26ZrIEOkCtreRi7TA=
addons:
  sauce_connect: true
env:
  global:
  - secure: Ot020jdOcMJpbDa5fcmDX8bzILLXmfDKSLAJ3nPNrIxmC8QK9Cs03W9s+UGrwwTMfdGHp3YKmQS8+TN2krc+ZIZhsi8shLDcpvZLL0oBqW0Ag8hscFFSPyLJfMuFfzw/zgCSW61XMOqyY5hndCnug8cNEGZhg8duDMML82raT/E=
  - secure: M6IFhWXYGHMwIxR1CPeu4gUpbj4N1lGFGo8BUz7mkEH6VHCWO2IyfHtIgjwi2nU9b7NnrS+Z7spYJxIU/ovXB6ixCUXFdMgAdYzFsY2kL8MEpjJRPYMUpbV8BrN/dRjp8b7kVzVFoPp9cpp8pKgpgxn/eoA2i1F4icuGOd1GDq0=
